FROM python
WORKDIR /app
COPY atlan.py .
RUN pip install flask
RUN pip install docker
RUN pip install flask_restful
RUN apt-get update
RUN apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
ENV FLASK_APP "atlan"
ENV FLASK_ENV "development"
ENV FLASK_RUN_HOST "0.0.0.0"
CMD ["flask", "run"]
